"""Add submit time coloum

Revision ID: 1be17cd7777b
Revises: 234633eb1485
Create Date: 2022-05-14 20:28:21.919251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be17cd7777b'
down_revision = '234633eb1485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_table', sa.Column('submit_time', sa.DateTime(), nullable=True))
    op.add_column('range_table', sa.Column('submit_time', sa.DateTime(), nullable=True))
    op.add_column('trip_table', sa.Column('submit_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_table', 'submit_time')
    op.drop_column('range_table', 'submit_time')
    op.drop_column('charging_table', 'submit_time')
    # ### end Alembic commands ###
