"""Add trip model

Revision ID: 58627ce4a028
Revises: 70929539524d
Create Date: 2022-05-01 11:40:02.974689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58627ce4a028'
down_revision = '70929539524d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miles', sa.Float(), nullable=True),
    sa.Column('kwh', sa.Float(), nullable=True),
    sa.Column('trip_time', sa.Interval(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_table')
    # ### end Alembic commands ###
