"""empty message

Revision ID: 70929539524d
Revises: 
Create Date: 2022-05-01 01:24:39.980915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70929539524d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('range_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battery_range', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('range_table')
    op.drop_table('charging_table')
    # ### end Alembic commands ###
