"""Add range to trip model

Revision ID: 9233c5f2fe40
Revises: a6a27dfb9df1
Create Date: 2022-05-26 18:51:41.690765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9233c5f2fe40'
down_revision = 'a6a27dfb9df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('range_table_trip_id_fkey', 'range_table', type_='foreignkey')
    op.drop_column('range_table', 'trip_id')
    op.add_column('trip_table', sa.Column('range_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trip_table', 'range_table', ['range_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_table', type_='foreignkey')
    op.drop_column('trip_table', 'range_id')
    op.add_column('range_table', sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('range_table_trip_id_fkey', 'range_table', 'trip_table', ['trip_id'], ['id'])
    # ### end Alembic commands ###
