name: "Deploy to Heroku"

on:
  push:
    tags:
      - "v**"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "car-api-dev"
          heroku_email: "carapi@cyberjake.xyz"
          usedocker: true